### ISSUE TITLE
Cannot (install) upgrade ooniprobe application

### ISSUE THREAD

**Issue by anadahz** [measurement-kit/ooniprobe-android#29]
### Description
Installing a newer version of ooniprobe application fails to install (upgrade).

### Steps to Reproduce
- Install [ooniprobe-android v0.1.0-rc](https://github.com/measurement-kit/ooniprobe-android/releases/tag/v0.1.0-rc)
- Install [ooniprobe-android v0.1.0-rc.2](https://github.com/measurement-kit/ooniprobe-android/releases/tag/v0.1.0-rc.2)

 **Expected behavior:** 
Install (upgrade) ooniprobe app ooniprobe-android v0.1.0-rc.2

**Actual behavior:**
Installation fails with the error:
`An existing package by the same name with a conflicting signature is already installed.`

**Comment by hellais** [comment]
If you uninstall v0.1.0-rc and then install v0.1.0-rc.2 are you able to get it up and running properly?

I believe the problem is that nuke created a signed apk with his signagure in `-rc` and I created an unsigned apk in `-rc.2`.

**Comment by bassosimone** [comment]
> I believe the problem is that nuke created a signed apk with his signagure in -rc and I created an unsigned apk in -rc.2.

Yes, this seems like a super convincing explanation to me!

**Comment by hellais** [comment]
I am going to add a note to the installation instructions saying that you must uninstall all previous versions of ooniprobe to "update"
